name = "SymbolicNeuralNetworks"
uuid = "aed23131-dcd0-47ca-8090-d21e605652e3"
authors = ["Michael Kraus"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
